package Modelo;
// Generated 26/10/2016 09:36:35 PM by Hibernate Tools 3.6.0



/**
 * ComponentesExternos generated by hbm2java
 */
public class ComponentesExternos  implements java.io.Serializable {


     private Integer idComponentesExternos;
     private String nombreExterno;
     private int cantidad;
     private int idVehiculo;

    public ComponentesExternos() {
    }

    public ComponentesExternos(String nombreExterno, int cantidad, int idVehiculo) {
       this.nombreExterno = nombreExterno;
       this.cantidad = cantidad;
       this.idVehiculo = idVehiculo;
    }
   
    public Integer getIdComponentesExternos() {
        return this.idComponentesExternos;
    }
    
    public void setIdComponentesExternos(Integer idComponentesExternos) {
        this.idComponentesExternos = idComponentesExternos;
    }
    public String getNombreExterno() {
        return this.nombreExterno;
    }
    
    public void setNombreExterno(String nombreExterno) {
        this.nombreExterno = nombreExterno;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }




}


