package Modelo;
// Generated 26/10/2016 09:36:35 PM by Hibernate Tools 3.6.0



/**
 * Llantas generated by hbm2java
 */
public class Llantas  implements java.io.Serializable {


     private Integer idLlantas;
     private int cantidad;
     private String marca;
     private int idVehiculo;

    public Llantas() {
    }

    public Llantas(int cantidad, String marca, int idVehiculo) {
       this.cantidad = cantidad;
       this.marca = marca;
       this.idVehiculo = idVehiculo;
    }
   
    public Integer getIdLlantas() {
        return this.idLlantas;
    }
    
    public void setIdLlantas(Integer idLlantas) {
        this.idLlantas = idLlantas;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }




}


